// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-SdSaEwh4TJTxwrcP6WEO0-J5jNZWuLI',
    appId: '1:565810147868:web:b495607a55743c580965d9',
    messagingSenderId: '565810147868',
    projectId: 'foreach-nosql',
    authDomain: 'foreach-nosql.firebaseapp.com',
    databaseURL: 'https://foreach-nosql-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'foreach-nosql.appspot.com',
    measurementId: 'G-PVWVR3QWF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA8wheu7m2ydRVDuGblXg18hI2l-MgIDA',
    appId: '1:565810147868:android:785bccca45e7c3820965d9',
    messagingSenderId: '565810147868',
    projectId: 'foreach-nosql',
    databaseURL: 'https://foreach-nosql-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'foreach-nosql.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGlrNmsViEEqNTdN2hqOUPefqAk6I9A7g',
    appId: '1:565810147868:ios:d7553e6354e8f9cd0965d9',
    messagingSenderId: '565810147868',
    projectId: 'foreach-nosql',
    databaseURL: 'https://foreach-nosql-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'foreach-nosql.appspot.com',
    iosClientId: '565810147868-9ge928osn47c20odl2jt44cvvgi3k1sh.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockManagement',
  );
}
